# Generated by Django 5.2.17 on 2026-09-23 16:58

import django.db.models.deletion
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_asset_dish"),
    ]

    operations = [
        migrations.AddField(
            model_name="menucandidate",
            name="choice_group_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="menucandidate",
            name="external_key",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="menucandidate",
            name="needs_photo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="menucandidate",
            name="needs_review",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="menucandidate",
            name="parent_key",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name="PaymentCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.models.uid, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("direction", models.CharField(blank=True, max_length=12)),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("merchant", models.CharField(blank=True, max_length=200)),
                ("paid_at_text", models.CharField(blank=True, max_length=100)),
                ("reference_hint", models.CharField(blank=True, max_length=20)),
                ("raw_result", models.JSONField(blank=True, default=dict)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_candidate",
                        to="core.asset",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.payment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
