# Generated by Django 5.2.17 on 2026-09-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_menucandidate_choice_group_name_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="evidencelink",
            constraint=models.UniqueConstraint(
                fields=("asset", "order", "payment"),
                name="unique_evidence_link",
                nulls_distinct=False,
            ),
        ),
    ]
