# Generated by Django 5.2.17 on 2026-10-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_evidencelink_unique_evidence_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisionConfiguration",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("manual", "手工录入"),
                            ("responses", "Responses API"),
                            ("chat_completions", "Chat Completions 兼容 API"),
                        ],
                        default="responses",
                        max_length=30,
                        verbose_name="识别模式",
                    ),
                ),
                (
                    "api_url",
                    models.URLField(
                        blank=True,
                        help_text="留空使用部署环境配置；须为 HTTPS，包含 /responses 或 /chat/completions。",
                        max_length=500,
                        verbose_name="完整 API 地址",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="填写服务商支持图片输入的模型名称；留空使用部署环境配置。",
                        max_length=150,
                        verbose_name="模型名称",
                    ),
                ),
            ],
            options={
                "verbose_name": "图片识别设置",
                "verbose_name_plural": "图片识别设置",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="single_vision_configuration"
                    )
                ],
            },
        ),
    ]
