from django.contrib.auth.views import PasswordChangeView
from django.urls import path, reverse_lazy

from . import web, web_exports, web_finance, web_recognition

urlpatterns = [
    path("", web.home, name="home"),
    path("tasks/", web.task_inbox, name="task-inbox"),
    path("me/", web.profile, name="profile"),
    path(
        "me/password/",
        PasswordChangeView.as_view(
            template_name="registration/password_change.html", success_url=reverse_lazy("profile")
        ),
        name="password-change",
    ),
    path("register/", web.register, name="register"),
    path("projects/new/", web.project_create, name="project-create"),
    path("projects/<uuid:pk>/", web.project_page, name="project"),
    path("projects/<uuid:pk>/overview/", web.project_overview, name="project-overview"),
    path("projects/<uuid:pk>/join/", web.project_join, name="project-join"),
    path("projects/<uuid:pk>/visits/new/", web.visit_create, name="visit-create"),
    path("projects/<uuid:pk>/status/", web.project_status, name="project-status"),
    path("projects/<uuid:pk>/invite/", web.invite_create, name="invite-create"),
    path("invitations/<uuid:pk>/revoke/", web.invite_revoke, name="invite-revoke"),
    path("join/<str:token>/", web.join, name="join"),
    path("visits/<uuid:pk>/", web.visit_page, name="visit"),
    path("visits/<uuid:pk>/status/", web.visit_status, name="visit-status"),
    path("visits/<uuid:pk>/settings/", web.visit_settings, name="visit-settings"),
    path("visits/<uuid:pk>/options/", web.options_generate, name="options-generate"),
    path("options/<uuid:pk>/vote/", web.vote, name="vote"),
    path("visits/<uuid:pk>/schedule/", web.schedule, name="schedule"),
    path("visits/<uuid:pk>/attendance/", web.attendance, name="attendance"),
    path("visits/<uuid:pk>/choices/", web.choice_create, name="choice-create"),
    path("visits/<uuid:pk>/dishes/", web.dish_create, name="dish-create"),
    path("dishes/<uuid:pk>/update/", web.dish_update, name="dish-update"),
    path("choices/<uuid:pk>/select/", web.choice_select, name="choice-select"),
    path("assignments/<uuid:pk>/claim/", web.assignment_claim, name="assignment-claim"),
    path("assignments/<uuid:pk>/submit/", web.assignment_submit, name="assignment-submit"),
    path("assignments/<uuid:pk>/manage/", web.assignment_manage, name="assignment-manage"),
    path("visits/<uuid:pk>/images/", web.image_upload, name="image-upload"),
    path("images/<uuid:pk>/download/", web.image_download, name="image-download"),
    path("images/<uuid:pk>/thumbnail/", web.image_thumbnail, name="image-thumbnail"),
    path("images/<uuid:pk>/select/", web.image_select, name="image-select"),
    path("dishes/<uuid:pk>/document/", web.dish_document, name="dish-document"),
    path("dishes/<uuid:pk>/my-document/", web.my_dish_document, name="my-dish-document"),
    path("projects/<uuid:pk>/document/", web.project_document, name="project-document"),
    path("documents/<uuid:pk>/", web.document_page, name="document"),
    path("documents/<uuid:pk>/save/", web.document_save, name="document-save"),
    path("documents/<uuid:pk>/comments/", web.comment_add, name="comment-add"),
    path("comments/<uuid:pk>/resolve/", web.comment_resolve, name="comment-resolve"),
    path("documents/<uuid:pk>/suggestions/", web.suggestion_add, name="suggestion-add"),
    path("suggestions/<uuid:pk>/decide/", web.suggestion_decide, name="suggestion-decide"),
    path("documents/<uuid:pk>/status/", web.document_status, name="document-status"),
    path("documents/<uuid:pk>/restore/", web.document_restore, name="document-restore"),
    path("projects/<uuid:pk>/compose/", web.document_compose, name="document-compose"),
    path("notifications/<uuid:pk>/read/", web.notification_read, name="notification-read"),
    path("projects/<uuid:pk>/reminders/", web.reminder_summary, name="reminder-summary"),
    path("visits/<uuid:pk>/finance/", web_finance.visit_page, name="finance-visit"),
    path("visits/<uuid:pk>/orders/", web_finance.order_create, name="order-create"),
    path("orders/<uuid:pk>/lines/", web_finance.line_create, name="line-create"),
    path("orders/<uuid:pk>/adjustments/", web_finance.adjustment_create, name="adjustment-create"),
    path("visits/<uuid:pk>/payments/", web_finance.payment_create, name="payment-create"),
    path(
        "payments/<uuid:pk>/allocations/", web_finance.allocation_create, name="allocation-create"
    ),
    path("payments/<uuid:pk>/refunds/", web_finance.refund_create, name="refund-create"),
    path("visits/<uuid:pk>/evidence/", web_finance.evidence_create, name="evidence-create"),
    path("projects/<uuid:pk>/claims/", web_exports.project_page, name="claims"),
    path("projects/<uuid:pk>/claims/new/", web_exports.create, name="claim-create"),
    path("claims/<uuid:pk>/", web_exports.claim_page, name="claim"),
    path("claims/<uuid:pk>/explain/", web_exports.explain, name="claim-explain"),
    path("claims/<uuid:pk>/export/", web_exports.generate, name="claim-export"),
    path("exports/<uuid:pk>/download/", web_exports.download, name="export-download"),
    path("projects/<uuid:pk>/content-export/", web_exports.content_generate, name="content-export"),
    path("visits/<uuid:pk>/recognition/", web_recognition.page, name="recognition"),
    path("assets/<uuid:pk>/recognize/", web_recognition.queue, name="recognition-queue"),
    path("jobs/<uuid:pk>/retry/", web_recognition.retry, name="job-retry"),
    path("menus/<uuid:pk>/confirm/", web_recognition.menu_confirm, name="menu-confirm"),
    path(
        "menu-candidates/<uuid:pk>/update/",
        web_recognition.menu_candidate_update,
        name="menu-candidate-update",
    ),
    path(
        "payment-candidates/<uuid:pk>/confirm/",
        web_recognition.payment_confirm,
        name="payment-confirm",
    ),
]
